also copy loadmyvars.sh, make template call newjail

diff --git a/bin/ioc-newtemplate b/bin/ioc-newtemplate
--- a/bin/ioc-newtemplate
+++ b/bin/ioc-newtemplate
@@ -12,62 +12,23 @@ if ! which iocage >/dev/null 2>&1 ; then
     exit 1
 fi
 
-
 TEMPLATE=${1}
 NICNET="${2}"
 
-pf-nat-jails
+ioc-newjail ${TEMPLATE} "${NICNET}"
 
-iocage create -c tag=${TEMPLATE} ip4_addr="${NICNET}"
-iocage set boot=off ${TEMPLATE}
+## start jail so it runs firstboot
+iocage start ${TEMPLATE}
 
-if ! ioc-pathof ${TEMPLATE} >/dev/null 2>&1; then
-    echo "ERROR: template not created."
+#echo "Setup the template however you like, then exit."
+## open console to wait
+#iocage console ${TEMPLATE}
+
+## stop jail
+iocage stop ${TEMPLATE}
+iocage set notes="template based on ${IOCRELEASE} with pkg-static, fres, psnap" ${TEMPLATE}
+iocage set template=yes ${TEMPLATE}
+if ! iocage list -t | grep "${TEMPLATE}$" >/dev/null 2>/dev/null ; then
+    echo "ERROR: template not converted from jail."
     exit 1
-else
-    ## create the firstboot_sentinel file
-    touch $( ioc-pathof ${TEMPLATE} )/firstboot
-    sysrc -f $( ioc-pathof ${TEMPLATE} )/etc/rc.conf.d/firstboot_jail firstboot_jail_enable=YES
-    SQUID=$( echo ${HTTP_PROXY} | awk -F/ '{print $NF}' )
-    if [ "x" != "x${SQUID}" ]; then
-        sysrc -f $( ioc-pathof ${TEMPLATE} )/etc/rc.conf.d/firstboot_jail firstboot_jail_squid="${SQUID}"
-    fi
-    ## install pkg-static
-    install -C -m 755 /usr/local/sbin/pkg-static  $( ioc-pathof ${TEMPLATE} )/sbin/pkg-static
-    ## install etc/files
-    for i in $( find ~/git/iocage-tools/etc -type f -maxdepth 1 ) ; do
-        if [ -f ${i} ]; then
-            install -C -m 644 ${i}  $( ioc-pathof ${TEMPLATE} )/etc/${i##*/}
-        fi
-    done
-    ## install etc/rc.d/files
-    for i in $( find ~/git/iocage-tools/etc/rc.d -type f -maxdepth 1 ) ; do
-        if [ -f ${i} ]; then
-            install -C -m 755 ${i}  $( ioc-pathof ${TEMPLATE} )/etc/rc.d/${i##*/}
-        fi
-    done
-
-    ## skip motd on jail console
-    touch $( ioc-pathof ${TEMPLATE} )/root/.hushlogin
-    ### install some scripts for firstboot
-    install -d -m 755 -o root -g wheel $( ioc-pathof ${JAILNAME} )/usr/local/bin
-    for i in setproxy fres psnap ; do
-        which $i >/dev/null 2>&1 && install -C -m 755 $(which $i) $( ioc-pathof ${JAILNAME} )/usr/local/bin/
-    done
-
-    ## start jail so it runs firstboot
-    iocage start ${TEMPLATE}
-
-    #echo "Setup the template however you like, then exit."
-    ## open console to wait
-    #iocage console ${TEMPLATE}
-
-    ## stop jail
-    iocage stop ${TEMPLATE}
-    iocage set notes="template based on ${IOCRELEASE} with pkg-static, fres, psnap" ${TEMPLATE}
-    iocage set template=yes ${TEMPLATE}
-    if ! iocage list -t | grep "${TEMPLATE}$" >/dev/null 2>/dev/null ; then
-        echo "ERROR: template not converted from jail."
-        exit 1
-    fi
 fi
