test for iocage

diff --git a/bin/ioc-newtemplate b/bin/ioc-newtemplate
--- a/bin/ioc-newtemplate
+++ b/bin/ioc-newtemplate
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if ! which iocage >/dev/null 2>&1 ; then
+    echo "ERROR: iocage not found."
+    exit 1
+fi
+
 
 TEMPLATE=${1}
 NICNET="${2}"
